name: Build Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARCH: arm64
      SUBARCH: arm64
      CROSS_COMPILE: aarch64-linux-android-

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang libncurses-dev libssl-dev bc flex bison \
            gcc-aarch64-linux-android

      - name: Prepare defconfig
        run: |
          make O=out defconfig

      - name: Build kernel
        run: |
          make -j$(nproc) O=out

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v2
        with:
          name: kernel-Image.gz-dtb
          path: out/arch/arm64/boot/Image.gz-dtb
